### ISSUE TITLE
switch to flakes (2.4 is released)

### ISSUE THREAD

**Issue by luxus** [shajra/shajra-provisioning#1]
hello,
nix 2.4 just got [released](https://discourse.nixos.org/t/nix-2-4-released/15822)
but it looks like flakes are still experimental.. 
how will this change your plans to switch to flakes with the 2.4 release?

I saw your config and it could be a good base for me.. and I love that you already have ci up and running.. but I would love to use nix flakes instead of niv

**Comment by shajra** [comment]
@luxus hi!

So I've always been frustrated at how long some things can just sit as experimental.  I get further annoyed when people insist that experimental things are actually stable.  But that all said, I might just set aside my annoyance and accept that flakes are "released enough" to give a shot.  I've just been a curmudgeon holdout up until now. 

I know topically what flakes do and are good for.  But I'm not sure to what degree it replaces my usage of Niv.  Maybe all of it?  I guess I have to find out.  I hope a full replacement is possible.  Using both Niv and flakes seems tedious and sad.

If it does pan out that flakes can completely replace Niv, then there's a whole cascade of my projects to do this replacement in.  I'm very likely going to try this first with a base project of mine, [Nix-project](https://github.com/shajra/nix-project), which wraps my usage of Niv for my preferred ergonomics.  After that, I'd expect to roll it out quickly across all my projects, this one included.

So I can't promise anything too soon.  I'm open to PRs, but I'm also very finicky when it comes to these Nix-y/script-y things and have a lot of hard to explain design sentiments.  Ultimately, I need to need to play around and refactor things until it feels right.

I'm glad you liked the project though.  It's felt really amazing to get my systems in good order with Nix.  I know a lot of people have projects like this, but I've enjoyed how this one came together for me.

**Comment by shajra** [comment]
Hi.  After a very long time, I finally switched to flakes.  See the `main` branch.  Thanks!

**Comment by luxus** [comment]
oh nice :D by now i have my own config but sure i will check it out
